name: SDKPublish
on:
  push:
    tags:
    - 'v*' 
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEVANCE_API_KEY: ${{ secrets.RELEVANCE_API_KEY }}
      RELEVANCE_PROJECT: ${{ secrets.RELEVANCE_PROJECT }}
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org/
    - name: Install modules
      run: npm install
    - name: Regenerate SDK
      run: npm run generate && npm run prepare
    - name: Set git identity
      run: (git config --global user.email "jssdkautomation@relevance.ai") && (git config --global user.name "jssdkautomation")
    - name: Publish to github and npm only if there has been a new change
      run: git diff-index --quiet HEAD || (git add . && npm version minor --force && git push && npm publish --access public)
