name: SDKPublish
on:
  push:
    tags:
    - 'v*' 
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org/
    - name: Install modules
      run: npm install
    - name: Regenerate SDK
      run: npm run generate && npm run prepare
    - name: Publish to npm
      run: npm publish --access public
