name: Publish

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download npm package artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: npm/
      
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm
          npm publish --dry-run --access public
  
  publish-jsr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      
      - name: Publish to JSR
        run: deno publish --token ${{ secrets.NPM_TOKEN }} --dry-run