name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  publish-npm:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Download npm package artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: npm/

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm
          npm publish --access public

  publish-jsr:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: ./.github/actions/setup-deno

      - name: Publish to JSR
        run: deno publish --token ${{ secrets.JSR_TOKEN }}
