name: Test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: ./.github/actions/setup-deno

      - name: Run tests
        run: deno test
